# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

mqtt:
    broker: mosquitto
    client_id: home-assistant
    discovery: true
    discovery_prefix: devices

# Text to speech
tts:
    -   platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
